version: '3.1'

services:
  db:
    image: postgres:13.10
    container_name: myproject-database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres